### ISSUE TITLE
Update to 0.6, code changes, Windows build, module test.

### ISSUE THREAD

**Issue by dizzisound** [dizzisound/VCV-Rack-Csound-Modules#1]
Branch v0.6 of this forked repo stores a version update of the _CsoundReverb_ module, to make it compliant with VCV Rack 0.6 API.
While porting the code, I added a few slight changes, so as to fix issues preventing the plugin to run on the Windows platform.
In brief, here are what has been modified:
- general update to VCVRack 0.6 API, as per this issue: https://github.com/VCVRack/Rack/issues/258 
- moved the _CsoundReverb.csd_ file to a separate **_csd_** folder, and added it to the distributables, as an external asset folder;
- changed the path to load the .csd resource, removing part of the hard-coded path and loading it relatively to the plugin location, via the `assetPlugin()` method (this fixed the failure in loading the .csd file when running the installed version of Rack under Windows);
- no more need to clone the repo into "Csound" folder (this as a consequence of the above);
- added conditional `dllexport `attribute implementation, as per this issue: https://github.com/Djack13/VCV-Rack-Csound-Modules/issues/3 
- modified the _Makefile_ adding a Windows conditional block, and including options for the Csound headers and library custom paths to be passed via command line (again, thanks to @rorywalsh for the solution posted in the issue beforehand mentioned).

About the last point, when building from source, one should call `make `passing in the CSOUND_INCLUDE and CSOUND_LIBRARY path parameters. Here an example of `make `command, based on the default installation path of the Csound program under Windows:
$ `make CSOUND_INCLUDE="c:/Program Files/Csound6_x64/include" CSOUND_LIBRARY="c:/Program Files/Csound6_x64/lib/"`
When not passing arguments, they default to the standard locations highlighted by @Djack13 in this issue: https://github.com/Djack13/VCV-Rack-Csound-Modules/issues/2 

Branch v0.6 was tested only under Windows 8.1 x64, against Rack 0.6.0.
Building with Linux or Mac wasn't tested, but it should work as before.
Testers and contributions would be very welcome, in order to move forward the project.

**Comment by ghost** [comment]
Hello,
Just tested on linux.
make gave the error message:
   src/Csound.hpp:14:1: error: ‘DLL_EXPORT’ does not name a type
 
With:
#if defined _WIN32 || defined __CYGWIN__
	DLL_EXPORT void init(rack::Plugin *p);
#else      //for linux
        void init(rack::Plugin *p);
#endif

compiled and tested ok

Please note:
Your message push me to upload my work on git, so i have deprecated the repository VCV-Rack-Csound-Modules and added the new one VCV_Csound.

Best,
René

**Comment by dizzisound** [comment]
@Djack13 Nice! Thanks for the tip. I just pushed the fix to this repo. So now I know the build keeps being "Linux-safe". Still lacking Mac test, but it's a minor issue by now, things are moving forward.

Btw, I've seen your new repo, already cloned and tried the build on Windows. With exactly the same adjustments posted here, the build completed successfully and all the modules loaded into Rack, either when run from the MinGW environment, or when launched from the Rack installed executable.

That push me to a question. I could fork the new repository VCV_Csound and submit a PR, should you wish so, aiming at cross-platform build integration for your new set of modules. Please tell me if this is your preferred way to go. Anyway, I'd better archive this repo, I fear it's confusing for devs and users trying to build on different platforms.

Congrats for your work, it's a awesome project to make VCV Rack and Csound play together!
Best,
Daniele

**Comment by ghost** [comment]
Hi Daniele,
Happy to help!

You have to know that i am not a programmer and i am French, so sorry for C++ bugs and English mistakes  :)

My knowledge is limited to linux and it is not so easy for me, my new modules works very well on my Linux Mint machine but there is an issue on Linux Fedora: module deletion crashes Rack.
Have to investigate!
So for now i prefer to stay away from Windows world :)
Hope you understand.
If you want i will add a link to your repository on my readme for Windows users.
Best,
René

**Comment by dizzisound** [comment]
Hi René, thanks for your reply.
No problem with English, I have the same communication gap!
I perfectly understand the "no-Windows" argument. Cross-platform issues are the main thing still preventing me from full plugin development...
So I have to think about furthermore Windows support to your Csound modules. It mostly depends on user demand and needs to come. I guess that Rack has a rather consistent Windows users base. At the other side, devs could more easily make their way by theirselves through the building issues.
I think of 2 possible ways to go:
1) Close this repo and wait for possible future needs for further Windows support/manteinance of your modules.
2) Fork the new VCV_Csound repo and mantain it in sync with your's original repo, adding only the few bits of code to makefile and headers to let it be compliant with the Windows platform.
I'll take some time to think about that.
In the meantime, I'll have some fun with your modules!
Have a good day,
best
Daniele

**Comment by dizzisound** [comment]
Closing this repo, moved to https://github.com/dizzisound/VCV_Csound
